services:
    icaplyon1_simpletag.manager:
        class: ICAPLyon1\Bundle\SimpleTagBundle\Service\Manager
        arguments: [@doctrine.orm.entity_manager]

    icaplyon1_type.tags:
        class: ICAPLyon1\Bundle\SimpleTagBundle\Form\TagsType
        arguments: []
        tags:
            - { name: form.type, alias: tags }